version: "3.8"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rainref
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  opa:
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "/policies"]
    volumes:
      - ../api/policies:/policies
    ports: ["8181:8181"]

  api:
    build: ../api
    env_file: ../api/.env
    ports: ["8080:8080"]
    depends_on: [db, opa]
    volumes:
      - ../api:/app

  web:
    build: ../web
    env_file: ../web/.env
    ports: ["5173:5173"]
    depends_on: [api]
    volumes:
      - ../web:/app
